// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXK9_yfeTCn20s31LzcbifLvGoAaExm5I',
    appId: '1:921272793737:web:b95c8b5ef6d84ab2c5e458',
    messagingSenderId: '921272793737',
    projectId: 'news-app-fcm',
    authDomain: 'news-app-fcm.firebaseapp.com',
    storageBucket: 'news-app-fcm.firebasestorage.app',
    measurementId: 'G-3NNB7QHVGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dJvOg_r10uPFUhnMzwDVkr5BJ4vGXIU',
    appId: '1:921272793737:android:a39bbdfc7744c777c5e458',
    messagingSenderId: '921272793737',
    projectId: 'news-app-fcm',
    storageBucket: 'news-app-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYPSg548wAWrQ5qUe-36tIQjGfuFQy7w',
    appId: '1:921272793737:ios:63aaa304c6572c67c5e458',
    messagingSenderId: '921272793737',
    projectId: 'news-app-fcm',
    storageBucket: 'news-app-fcm.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYPSg548wAWrQ5qUe-36tIQjGfuFQy7w',
    appId: '1:921272793737:ios:63aaa304c6572c67c5e458',
    messagingSenderId: '921272793737',
    projectId: 'news-app-fcm',
    storageBucket: 'news-app-fcm.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXK9_yfeTCn20s31LzcbifLvGoAaExm5I',
    appId: '1:921272793737:web:7e603591c5e88b2dc5e458',
    messagingSenderId: '921272793737',
    projectId: 'news-app-fcm',
    authDomain: 'news-app-fcm.firebaseapp.com',
    storageBucket: 'news-app-fcm.firebasestorage.app',
    measurementId: 'G-GTRMDV2RXH',
  );
}
